name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  
  # Cho phép chạy workflow này thủ công từ tab Actions
  workflow_dispatch:

# Thiết lập quyền để job cập nhật GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Cho phép một lần triển khai đồng thời
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm install -g vite
          vite build --config vite.github-pages.config.js
      - name: Create extra files
        run: |
          touch dist/.nojekyll
          cp dist/index.html dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Job triển khai
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
